CREATE DATABASE  IF NOT EXISTS `magnitDB`;
USE magnitDB;
DROP TABLE IF EXISTS TEST;
CREATE TABLE TEST (
  FIELD int(20) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE USER magnit@localhost IDENTIFIED BY 'magnit';
GRANT ALL PRIVILEGES ON magnitDB.TEST TO magnit@localhost;
FLUSH PRIVILEGES;

